name: Update OPKL
author: mrjoelkamp
description: Updates an OIDC provider public key ledger
inputs:
  provider_uri:
    description: OIDC provider discovery URI
    required: true
    default: https://token.actions.githubusercontent.com
  tuf_path:
    description: Path to root of TUF repo
    required: true
    default: /github/workspace
runs:
  using: docker
  image: docker://docker/jwkstuf:latest
  args:
    - /opt/jwkstuf/bin/jwkstuf
    - update
    - ${{ inputs.provider_uri }}
  env:
    JWKSTUF_PATH: ${{ inputs.tuf_path }}
